kind: pipeline
name: default
type: docker
trigger:
  event:
    - push

steps:
  - name: django-tests
    image: python
    commands:
      - pip install -r requirements.txt
      - pip install -r requirements-dev.txt
      - echo 'SECRET_KEY = "Test"' > vulnman/conf/secret_key.py
      - python manage.py create_secret_key
      - python manage.py test

  - name: ssh
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: vulnman-staging-host
      username: vulnman
      key:
        from_secret: vulnman-ssh-key
      port: 22
      command_timeout: 10m
      script:
        - cd /opt/vulnman
        - git pull
        - python3 manage.py migrate
        - python manage.py collectstatic --noinput
        - sudo /opt/vulnman-helpers/update_blockomat_library.sh
        - python3 manage.py import_vulnerability_templates blockomat_vulnman
    when:
      branch:
        - main
      event:
        - push

---

kind: pipeline
type: docker
name: check-dependencies

trigger:
  event:
    - cron
    - push
  cron:
    - check-dependencies

steps:
  - name: renovate
    image: renovate/renovate
    environment:
      root_ca:
        from_secret: staging-root-ca
      NODE_EXTRA_CA_CERTS: /etc/ssl/certs/ca-certificates.crt
      LOG_LEVEL: debug
      RENOVATE_TOKEN:
        from_secret: RENOVATE_TOKEN
      RENOVATE_USERNAME:
        from_secret: RENOVATE_USERNAME
      RENOVATE_GIT_URL:
        from_secret: RENOVATE_GIT_URL
    commands:
      - renovate --platform gitea vulnman/vulnman --endpoint $RENOVATE_GIT_URL