version: "3.9"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=vulnman
      - POSTGRES_USER=vulnman
      - POSTGRES_PASSWORD=vulnman
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=vulnman
      - POSTGRES_USER=vulnman
      - POSTGRES_PASSWORD=vulnman
    depends_on:
      - db